import React from 'react';

const WhySection: React.FC = () => {
  return (
    <section id="why">
      <div className="why-layout">
        <div>
          <div className="section-chip reveal">Growth Partnerships</div>
          <h2 className="why-title reveal d1">Structural Alignment for <em>Sustained Scale.</em></h2>
          
          <p className="why-desc reveal d2 desktop-only">
            A Growth Partnership is a long-term operating agreement where we tie a portion of our compensation directly to the commercial outcomes generated by our systems.
          </p>
          <p className="why-desc reveal d2 mobile-only">
            A Growth Partnership aligns our compensation with your commercial outcomes.
          </p>

          <div className="why-slogan reveal d3 desktop-only">
            This model replaces traditional hourly billing with structural alignment over a multi-year horizon.
          </div>
          <div className="why-slogan reveal d3 mobile-only">
            Structural alignment over a multi-year horizon.
          </div>
          
          <a href="#book" className="btn-fill reveal d4" style={{ width: 'fit-content', marginTop: '28px' }}>
            Start a Conversation
          </a>
        </div>

        <div className="reveal d2" style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
          {/* Card 1 */}
          <div className="rebrand-card">
            <h3 style={{ fontFamily: 'var(--serif)', fontSize: '22px', fontWeight: 400, color: 'var(--ink)', marginBottom: '10px' }}>Systems Thinking</h3>
            <p style={{ fontSize: '13px', color: 'var(--sub)', lineHeight: '1.7' }}>We view every business as an interconnected architecture. A failure in customer retention is often a failure in operational data flow. We diagnose and resolve structural roots.</p>
          </div>
          
          {/* Card 2 */}
          <div className="rebrand-card">
            <h3 style={{ fontFamily: 'var(--serif)', fontSize: '22px', fontWeight: 400, color: 'var(--ink)', marginBottom: '10px' }}>Long-Term Alignment</h3>
            <p style={{ fontSize: '13px', color: 'var(--sub)', lineHeight: '1.7' }}>We reject the adversarial dynamic of hourly billing. We tie our financial success directly to outcomes. We build infrastructure designed to endure, because our model depends on its continued performance.</p>
          </div>

          {/* Card 3 (Case Study) */}
          <div className="rebrand-card rebrand-card-accent">
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '8px' }}>
              <span style={{ fontSize: '9px', fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', color: 'var(--b)', background: 'rgba(22,65,245,0.08)', padding: '2px 8px', borderRadius: '4px' }}>PRINCIPLE</span>
            </div>
            <h3 style={{ fontFamily: 'var(--serif)', fontSize: '22px', fontWeight: 400, color: 'var(--ink)', marginBottom: '10px' }}>Uncompromising Standards</h3>
            <p style={{ fontSize: '13px', color: 'var(--sub)', lineHeight: '1.7' }}>Execution is the only metric that matters. We do not deliver theoretical slide decks. We engineer, deploy, and maintain live operational systems. We hold ourselves accountable for the tangible reality of the implementation.</p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default WhySection;
